# Generated by Django 5.0 on 2024-05-18 22:27

import clickhouse_backend.models
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', clickhouse_backend.models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', clickhouse_backend.models.DateTime64Field(auto_now_add=True)),
                ('modified', clickhouse_backend.models.DateTime64Field(auto_now=True)),
                ('path', clickhouse_backend.models.FixedStringField(max_bytes=256)),
                ('clickhouse_db_name', clickhouse_backend.models.FixedStringField(max_bytes=200)),
                ('clickhouse_table_name', clickhouse_backend.models.FixedStringField(max_bytes=200)),
                ('column_names', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.FixedStringField(max_bytes=256), default=list)),
                ('context', clickhouse_backend.models.StringField(default='')),
            ],
            options={
                'verbose_name_plural': 'Datasets',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DataQuery',
            fields=[
                ('id', clickhouse_backend.models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', clickhouse_backend.models.DateTime64Field(auto_now_add=True)),
                ('user_prompt', clickhouse_backend.models.StringField()),
                ('command_query', clickhouse_backend.models.StringField()),
                ('chart_type', clickhouse_backend.models.FixedStringField(default='pie', max_bytes=50)),
                ('request_status', clickhouse_backend.models.FixedStringField(choices=[('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_bytes=10)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
            ],
            options={
                'verbose_name_plural': 'DataQueries',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='DynamicChart',
            fields=[
                ('id', clickhouse_backend.models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title_xaxis', clickhouse_backend.models.FixedStringField(max_bytes=50)),
                ('title_yaxis', clickhouse_backend.models.FixedStringField(max_bytes=50)),
                ('data_xaxis', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.Float64Field(), default=list)),
                ('data_yaxis', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.Float64Field(), default=list)),
                ('chart_type', clickhouse_backend.models.FixedStringField(max_bytes=50)),
                ('is_saved', clickhouse_backend.models.BoolField()),
                ('data_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dataquery')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ExportTable',
            fields=[
                ('id', clickhouse_backend.models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file_type', clickhouse_backend.models.FixedStringField(max_bytes=10)),
                ('url', clickhouse_backend.models.StringField()),
                ('request_status', clickhouse_backend.models.FixedStringField(choices=[('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_bytes=10)),
                ('data_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dataquery')),
            ],
            options={
                'verbose_name_plural': 'ExportTables',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', clickhouse_backend.models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', clickhouse_backend.models.DateTime64Field(auto_now_add=True)),
                ('user_prompt', clickhouse_backend.models.StringField()),
                ('activate_context', clickhouse_backend.models.BoolField(default=False)),
                ('gpt_response', clickhouse_backend.models.StringField()),
                ('request_status', clickhouse_backend.models.FixedStringField(choices=[('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_bytes=10)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
            ],
            options={
                'verbose_name_plural': 'Insights',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StaticChart',
            fields=[
                ('id', clickhouse_backend.models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title_xaxis', clickhouse_backend.models.FixedStringField(max_bytes=50)),
                ('title_yaxis', clickhouse_backend.models.FixedStringField(max_bytes=50)),
                ('data_xaxis', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.Float64Field(), default=list)),
                ('data_yaxis', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.Float64Field(), default=list)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
            ],
            options={
                'verbose_name_plural': 'StaticCharts',
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SummaryData',
            fields=[
                ('id', clickhouse_backend.models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('metrics', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.FixedStringField(max_bytes=256), default=list)),
                ('values', clickhouse_backend.models.ArrayField(base_field=clickhouse_backend.models.Float64Field(), default=list)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('_overwrite_base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
