# Generated by Django 5.0 on 2024-05-09 18:59

import django.db.models.deletion
import django_extensions.db.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('path', models.CharField(max_length=256)),
                ('clickhouse_table_name', models.CharField(max_length=200)),
                ('clickhouse_db_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Datasets',
            },
        ),
        migrations.CreateModel(
            name='DataQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('user_prompt', models.TextField()),
                ('command_query', models.TextField()),
                ('request_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=10)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
            ],
            options={
                'verbose_name_plural': 'DataQueries',
            },
        ),
        migrations.CreateModel(
            name='DynamicChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_xaxis', models.CharField(max_length=50)),
                ('title_yaxis', models.CharField(max_length=50)),
                ('chart_type', models.CharField(max_length=10)),
                ('is_saved', models.BooleanField()),
                ('data_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dataquery')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExportTable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('file_type', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('request_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=10)),
                ('data_query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dataquery')),
            ],
            options={
                'verbose_name_plural': 'ExportTables',
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1, verbose_name='status')),
                ('activate_date', models.DateTimeField(blank=True, help_text='keep empty for an immediate activation', null=True)),
                ('deactivate_date', models.DateTimeField(blank=True, help_text='keep empty for indefinite activation', null=True)),
                ('user_prompt', models.TextField()),
                ('activate_context', models.BooleanField()),
                ('gpt_response', models.TextField()),
                ('request_status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], max_length=10)),
                ('dataset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
            ],
            options={
                'verbose_name_plural': 'Insights',
            },
        ),
        migrations.CreateModel(
            name='StaticChart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_xaxis', models.CharField(max_length=50)),
                ('title_yaxis', models.CharField(max_length=50)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
            ],
            options={
                'verbose_name_plural': 'StaticCharts',
            },
        ),
        migrations.CreateModel(
            name='SummaryData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('dataset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.dataset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
