# Generated by Django 5.0 on 2024-05-20 13:40

import clickhouse_backend.models
import uuid
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataquery',
            name='task_id',
            field=clickhouse_backend.models.UUIDField(default=uuid.uuid4),
        ),
    ]
