# Generated by Django 5.0 on 2024-05-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dataquery_chart_type_alter_dataquery_dataset_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataquery',
            name='chart_type',
            field=models.CharField(default='pie', max_length=10),
        ),
    ]
