# Generated by Django 5.0 on 2024-05-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dataquery_managers_alter_dataset_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataquery',
            old_name='upload_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='upload_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='dataset',
            old_name='last_modification_date',
            new_name='modified',
        ),
        migrations.RenameField(
            model_name='insight',
            old_name='upload_date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='dataquery',
            name='last_modification_date',
        ),
        migrations.RemoveField(
            model_name='insight',
            name='last_modification_date',
        ),
    ]
